import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/lib/auth";
import Link from "next/link";
import AuthButtons from "@/components/authButtons";
import { HomeIcon } from "lucide-react";
import NotAuthButtons from "@/components/not-auth-buttons";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex h-24 flex-row justify-between bg-sky-900 p-10 text-white">
          <Link
            href={"./"}
            className="flex flex-row items-center gap-2 text-2xl tracking-widest uppercase"
          >
            <HomeIcon />
            <span>HouseLy</span>
          </Link>
          <ul className="flex flex-row items-center gap-6">
            <li>
              <Link
                href={"property-search"}
                className="rounded-lg p-1 tracking-widest uppercase hover:bg-sky-500"
              >
                property search
              </Link>
            </li>
            <li>
              {!!session?.user && <AuthButtons user={session?.user ?? null} />}
            </li>
            <li>{!session?.user && <NotAuthButtons />}</li>
          </ul>
          
        </nav>
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
